export const WATCHLIST = [
  {
    id: 1,
    name: "Watchlist 1",
    theme: "#1B9C85",
    stocks: [
      {
        stockName: "Infosys Ltd",
        symbol: "Infy",
        market: "NSE",
        pricePoints: [
          { date: "11 Apr 2023", amount: 4000 },
          { date: "12 Apr 2023", amount: 3000 },
          { date: "13 Apr 2023", amount: 2000 },
          { date: "14 Apr 2023", amount: 2780 },
          { date: "15 Apr 2023", amount: 1890 },
          { date: "16 Apr 2023", amount: 2390 },
          { date: "17 Apr 2023", amount: 3490 },
        ],
        volume: {
          total: 2898053,
          lastTradeQty: 500,
          lc: 936.46,
          uc: 984.2,
        },
        priceIndicators: {
          open: 960.0,
          close: 950.8,
          high: 945.2,
          low: 960.0,
          avgTradePrice: 952.03,
        },
        orderBook: {
          buy: {
            totalQty: 1611349,
            orders: [
              {
                qty: 195,
                totalOrders: 1109,
                price: 950.15,
                volumeFilled: 55,
              },
              {
                qty: 8,
                totalOrders: 1109,
                price: 951.0,
                volumeFilled: 5,
              },
              {
                qty: 100,
                totalOrders: 1109,
                price: 949.8,
                volumeFilled: 26,
              },
              {
                qty: 250,
                totalOrders: 1109,
                price: 949.65,
                volumeFilled: 85,
              },
              {
                qty: 51,
                totalOrders: 1109,
                price: 950.57,
                volumeFilled: 35,
              },
            ],
          },
          sell: {
            totalQty: 1504112,
            orders: [
              {
                qty: 10,
                totalOrders: 1110,
                price: 950.17,
                volumeFilled: 10,
              },
              {
                qty: 22,
                totalOrders: 2330,
                price: 951.2,
                volumeFilled: 12,
              },
              {
                qty: 1,
                totalOrders: 1119,
                price: 950.49,
                volumeFilled: 4,
              },
              {
                qty: 28,
                totalOrders: 900,
                price: 950.58,
                volumeFilled: 10,
              },
              {
                qty: 100,
                totalOrders: 1110,
                price: 951.9,
                volumeFilled: 38,
              },
            ],
          },
        },
      },
      {
        stockName: "Tata Motors Ltd",
        symbol: "TataMotors",
        market: "BSE",
        pricePoints: [
          { date: "11 Apr 2023", amount: 2400 },
          { date: "12 Apr 2023", amount: 1398 },
          { date: "13 Apr 2023", amount: 9800 },
          { date: "14 Apr 2023", amount: 3908 },
          { date: "15 Apr 2023", amount: 4800 },
          { date: "16 Apr 2023", amount: 3800 },
          { date: "17 Apr 2023", amount: 4300 },
        ],
        volume: {
          total: 2898053,
          lastTradeQty: 500,
          lc: 936.46,
          uc: 984.2,
        },
        priceIndicators: {
          open: 960.0,
          close: 950.8,
          high: 945.2,
          low: 960.0,
          avgTradePrice: 952.03,
        },
        orderBook: {
          buy: {
            totalQty: 1611349,
            orders: [
              {
                qty: 195,
                totalOrders: 1109,
                price: 950.15,
                volumeFilled: 55,
              },
              {
                qty: 8,
                totalOrders: 1109,
                price: 951.0,
                volumeFilled: 5,
              },
              {
                qty: 100,
                totalOrders: 1109,
                price: 949.8,
                volumeFilled: 26,
              },
              {
                qty: 250,
                totalOrders: 1109,
                price: 949.65,
                volumeFilled: 85,
              },
              {
                qty: 51,
                totalOrders: 1109,
                price: 950.57,
                volumeFilled: 35,
              },
            ],
          },
          sell: {
            totalQty: 1504112,
            orders: [
              {
                qty: 10,
                totalOrders: 1110,
                price: 950.17,
                volumeFilled: 10,
              },
              {
                qty: 22,
                totalOrders: 2330,
                price: 951.2,
                volumeFilled: 12,
              },
              {
                qty: 1,
                totalOrders: 1119,
                price: 950.49,
                volumeFilled: 4,
              },
              {
                qty: 28,
                totalOrders: 900,
                price: 950.58,
                volumeFilled: 10,
              },
              {
                qty: 100,
                totalOrders: 1110,
                price: 951.9,
                volumeFilled: 38,
              },
            ],
          },
        },
      },
      {
        stockName: "State Bank of India",
        symbol: "SBIN",
        market: "NSE",
        pricePoints: [
          { date: "11 Apr 2023", amount: 2400 },
          { date: "12 Apr 2023", amount: 2210 },
          { date: "13 Apr 2023", amount: 2290 },
          { date: "14 Apr 2023", amount: 2000 },
          { date: "15 Apr 2023", amount: 2181 },
          { date: "16 Apr 2023", amount: 2500 },
          { date: "17 Apr 2023", amount: 2100 },
        ],
        volume: {
          total: 2898053,
          lastTradeQty: 500,
          lc: 936.46,
          uc: 984.2,
        },
        priceIndicators: {
          open: 960.0,
          close: 950.8,
          high: 945.2,
          low: 960.0,
          avgTradePrice: 952.03,
        },
        orderBook: {
          buy: {
            totalQty: 1611349,
            orders: [
              {
                qty: 195,
                totalOrders: 1109,
                price: 950.15,
                volumeFilled: 55,
              },
              {
                qty: 8,
                totalOrders: 1109,
                price: 951.0,
                volumeFilled: 5,
              },
              {
                qty: 100,
                totalOrders: 1109,
                price: 949.8,
                volumeFilled: 26,
              },
              {
                qty: 250,
                totalOrders: 1109,
                price: 949.65,
                volumeFilled: 85,
              },
              {
                qty: 51,
                totalOrders: 1109,
                price: 950.57,
                volumeFilled: 35,
              },
            ],
          },
          sell: {
            totalQty: 1504112,
            orders: [
              {
                qty: 10,
                totalOrders: 1110,
                price: 950.17,
                volumeFilled: 10,
              },
              {
                qty: 22,
                totalOrders: 2330,
                price: 951.2,
                volumeFilled: 12,
              },
              {
                qty: 1,
                totalOrders: 1119,
                price: 950.49,
                volumeFilled: 4,
              },
              {
                qty: 28,
                totalOrders: 900,
                price: 950.58,
                volumeFilled: 10,
              },
              {
                qty: 100,
                totalOrders: 1110,
                price: 951.9,
                volumeFilled: 38,
              },
            ],
          },
        },
      },
    ],
  },
  {
    id: 2,
    name: "Watchlist 2",
    theme: "#4C4C6D",
    stocks: [
      {
        stockName: "Tata Motors Ltd",
        symbol: "TataMotors",
        market: "BSE",
        pricePoints: [
          { date: "11 Apr 2023", amount: 2400 },
          { date: "12 Apr 2023", amount: 1398 },
          { date: "13 Apr 2023", amount: 9800 },
          { date: "14 Apr 2023", amount: 3908 },
          { date: "15 Apr 2023", amount: 4800 },
          { date: "16 Apr 2023", amount: 3800 },
          { date: "17 Apr 2023", amount: 4300 },
        ],
        volume: {
          total: 2898053,
          lastTradeQty: 500,
          lc: 936.46,
          uc: 984.2,
        },
        priceIndicators: {
          open: 960.0,
          close: 950.8,
          high: 945.2,
          low: 960.0,
          avgTradePrice: 952.03,
        },
        orderBook: {
          buy: {
            totalQty: 1611349,
            orders: [
              {
                qty: 195,
                totalOrders: 1109,
                price: 950.15,
                volumeFilled: 55,
              },
              {
                qty: 8,
                totalOrders: 1109,
                price: 951.0,
                volumeFilled: 5,
              },
              {
                qty: 100,
                totalOrders: 1109,
                price: 949.8,
                volumeFilled: 26,
              },
              {
                qty: 250,
                totalOrders: 1109,
                price: 949.65,
                volumeFilled: 85,
              },
              {
                qty: 51,
                totalOrders: 1109,
                price: 950.57,
                volumeFilled: 35,
              },
            ],
          },
          sell: {
            totalQty: 1504112,
            orders: [
              {
                qty: 10,
                totalOrders: 1110,
                price: 950.17,
                volumeFilled: 10,
              },
              {
                qty: 22,
                totalOrders: 2330,
                price: 951.2,
                volumeFilled: 12,
              },
              {
                qty: 1,
                totalOrders: 1119,
                price: 950.49,
                volumeFilled: 4,
              },
              {
                qty: 28,
                totalOrders: 900,
                price: 950.58,
                volumeFilled: 10,
              },
              {
                qty: 100,
                totalOrders: 1110,
                price: 951.9,
                volumeFilled: 38,
              },
            ],
          },
        },
      },
    ],
  },
  {
    id: 3,
    name: "Watchlist 3",
    theme: "#EB6440",
    stocks: [
      {
        stockName: "State Bank of India",
        symbol: "SBIN",
        market: "NSE",
        pricePoints: [
          { date: "11 Apr 2023", amount: 2400 },
          { date: "12 Apr 2023", amount: 2210 },
          { date: "13 Apr 2023", amount: 2290 },
          { date: "14 Apr 2023", amount: 2000 },
          { date: "15 Apr 2023", amount: 2181 },
          { date: "16 Apr 2023", amount: 2500 },
          { date: "17 Apr 2023", amount: 2100 },
        ],
        volume: {
          total: 2898053,
          lastTradeQty: 500,
          lc: 936.46,
          uc: 984.2,
        },
        priceIndicators: {
          open: 960.0,
          close: 950.8,
          high: 945.2,
          low: 960.0,
          avgTradePrice: 952.03,
        },
        orderBook: {
          buy: {
            totalQty: 1611349,
            orders: [
              {
                qty: 195,
                totalOrders: 1109,
                price: 950.15,
                volumeFilled: 55,
              },
              {
                qty: 8,
                totalOrders: 1109,
                price: 951.0,
                volumeFilled: 5,
              },
              {
                qty: 100,
                totalOrders: 1109,
                price: 949.8,
                volumeFilled: 26,
              },
              {
                qty: 250,
                totalOrders: 1109,
                price: 949.65,
                volumeFilled: 85,
              },
              {
                qty: 51,
                totalOrders: 1109,
                price: 950.57,
                volumeFilled: 35,
              },
            ],
          },
          sell: {
            totalQty: 1504112,
            orders: [
              {
                qty: 10,
                totalOrders: 1110,
                price: 950.17,
                volumeFilled: 10,
              },
              {
                qty: 22,
                totalOrders: 2330,
                price: 951.2,
                volumeFilled: 12,
              },
              {
                qty: 1,
                totalOrders: 1119,
                price: 950.49,
                volumeFilled: 4,
              },
              {
                qty: 28,
                totalOrders: 900,
                price: 950.58,
                volumeFilled: 10,
              },
              {
                qty: 100,
                totalOrders: 1110,
                price: 951.9,
                volumeFilled: 38,
              },
            ],
          },
        },
      },
      {
        stockName: "Tata Motors Ltd",
        symbol: "TataMotors",
        market: "BSE",
        pricePoints: [
          { date: "11 Apr 2023", amount: 2400 },
          { date: "12 Apr 2023", amount: 1398 },
          { date: "13 Apr 2023", amount: 9800 },
          { date: "14 Apr 2023", amount: 3908 },
          { date: "15 Apr 2023", amount: 4800 },
          { date: "16 Apr 2023", amount: 3800 },
          { date: "17 Apr 2023", amount: 4300 },
        ],
        volume: {
          total: 2898053,
          lastTradeQty: 500,
          lc: 936.46,
          uc: 984.2,
        },
        priceIndicators: {
          open: 960.0,
          close: 950.8,
          high: 945.2,
          low: 960.0,
          avgTradePrice: 952.03,
        },
        orderBook: {
          buy: {
            totalQty: 1611349,
            orders: [
              {
                qty: 195,
                totalOrders: 1109,
                price: 950.15,
                volumeFilled: 55,
              },
              {
                qty: 8,
                totalOrders: 1109,
                price: 951.0,
                volumeFilled: 5,
              },
              {
                qty: 100,
                totalOrders: 1109,
                price: 949.8,
                volumeFilled: 26,
              },
              {
                qty: 250,
                totalOrders: 1109,
                price: 949.65,
                volumeFilled: 85,
              },
              {
                qty: 51,
                totalOrders: 1109,
                price: 950.57,
                volumeFilled: 35,
              },
            ],
          },
          sell: {
            totalQty: 1504112,
            orders: [
              {
                qty: 10,
                totalOrders: 1110,
                price: 950.17,
                volumeFilled: 10,
              },
              {
                qty: 22,
                totalOrders: 2330,
                price: 951.2,
                volumeFilled: 12,
              },
              {
                qty: 1,
                totalOrders: 1119,
                price: 950.49,
                volumeFilled: 4,
              },
              {
                qty: 28,
                totalOrders: 900,
                price: 950.58,
                volumeFilled: 10,
              },
              {
                qty: 100,
                totalOrders: 1110,
                price: 951.9,
                volumeFilled: 38,
              },
            ],
          },
        },
      },
    ],
  },
  {
    id: 4,
    name: "Watchlist 4",
    theme: "#B33030",
    stocks: [
      {
        stockName: "Infosys Ltd",
        symbol: "Infy",
        market: "NSE",
        pricePoints: [
          { date: "11 Apr 2023", amount: 4000 },
          { date: "12 Apr 2023", amount: 3000 },
          { date: "13 Apr 2023", amount: 2000 },
          { date: "14 Apr 2023", amount: 2780 },
          { date: "15 Apr 2023", amount: 1890 },
          { date: "16 Apr 2023", amount: 2390 },
          { date: "17 Apr 2023", amount: 3490 },
        ],
        volume: {
          total: 2898053,
          lastTradeQty: 500,
          lc: 936.46,
          uc: 984.2,
        },
        priceIndicators: {
          open: 960.0,
          close: 950.8,
          high: 945.2,
          low: 960.0,
          avgTradePrice: 952.03,
        },
        orderBook: {
          buy: {
            totalQty: 1611349,
            orders: [
              {
                qty: 195,
                totalOrders: 1109,
                price: 950.15,
                volumeFilled: 55,
              },
              {
                qty: 8,
                totalOrders: 1109,
                price: 951.0,
                volumeFilled: 5,
              },
              {
                qty: 100,
                totalOrders: 1109,
                price: 949.8,
                volumeFilled: 26,
              },
              {
                qty: 250,
                totalOrders: 1109,
                price: 949.65,
                volumeFilled: 85,
              },
              {
                qty: 51,
                totalOrders: 1109,
                price: 950.57,
                volumeFilled: 35,
              },
            ],
          },
          sell: {
            totalQty: 1504112,
            orders: [
              {
                qty: 10,
                totalOrders: 1110,
                price: 950.17,
                volumeFilled: 10,
              },
              {
                qty: 22,
                totalOrders: 2330,
                price: 951.2,
                volumeFilled: 12,
              },
              {
                qty: 1,
                totalOrders: 1119,
                price: 950.49,
                volumeFilled: 4,
              },
              {
                qty: 28,
                totalOrders: 900,
                price: 950.58,
                volumeFilled: 10,
              },
              {
                qty: 100,
                totalOrders: 1110,
                price: 951.9,
                volumeFilled: 38,
              },
            ],
          },
        },
      },
    ],
  },
  {
    id: 5,
    name: "Watchlist 5",
    theme: "#F08C00",
    stocks: [
      {
        stockName: "ITC Limited",
        symbol: "ITC",
        market: "NSE",
        pricePoints: [
          { date: "11 Apr 2023", amount: 324 },
          { date: "12 Apr 2023", amount: 223 },
          { date: "13 Apr 2023", amount: 134 },
          { date: "14 Apr 2023", amount: 154 },
          { date: "15 Apr 2023", amount: 215 },
          { date: "16 Apr 2023", amount: 343 },
          { date: "17 Apr 2023", amount: 288 },
        ],
        volume: {
          total: 2898053,
          lastTradeQty: 500,
          lc: 936.46,
          uc: 984.2,
        },
        priceIndicators: {
          open: 960.0,
          close: 950.8,
          high: 945.2,
          low: 960.0,
          avgTradePrice: 952.03,
        },
        orderBook: {
          buy: {
            totalQty: 1611349,
            orders: [
              {
                qty: 195,
                totalOrders: 1109,
                price: 950.15,
                volumeFilled: 55,
              },
              {
                qty: 8,
                totalOrders: 1109,
                price: 951.0,
                volumeFilled: 5,
              },
              {
                qty: 100,
                totalOrders: 1109,
                price: 949.8,
                volumeFilled: 26,
              },
              {
                qty: 250,
                totalOrders: 1109,
                price: 949.65,
                volumeFilled: 85,
              },
              {
                qty: 51,
                totalOrders: 1109,
                price: 950.57,
                volumeFilled: 35,
              },
            ],
          },
          sell: {
            totalQty: 1504112,
            orders: [
              {
                qty: 10,
                totalOrders: 1110,
                price: 950.17,
                volumeFilled: 10,
              },
              {
                qty: 22,
                totalOrders: 2330,
                price: 951.2,
                volumeFilled: 12,
              },
              {
                qty: 1,
                totalOrders: 1119,
                price: 950.49,
                volumeFilled: 4,
              },
              {
                qty: 28,
                totalOrders: 900,
                price: 950.58,
                volumeFilled: 10,
              },
              {
                qty: 100,
                totalOrders: 1110,
                price: 951.9,
                volumeFilled: 38,
              },
            ],
          },
        },
      },
    ],
  },
];
